### ISSUE TITLE
Line 32, The destination has an extra ~

### ISSUE THREAD

**Issue by rubenvarela** [chris-etheridge/lockscreen-magick#6]
Quick bug that I just saw

On [line 32](https://github.com/biscuitpants/blurred-lockscreen/blob/master/lock.sh#L32), the destination path has an extra `~` in the beginning.

```
~${STORAGE_DIR}/bak.png
```

Should be 

```
${STORAGE_DIR}/bak.png
```

This was introduced in [Pull 2](https://github.com/biscuitpants/blurred-lockscreen/pull/2) by me (sorry about that.)

**Comment by chrisetheridge** [comment]
Thank you! In the next commit.
